const CAR_MARK = [
  {
    value: "TOYOTA",
    label: "TOYOTA",
  },
  {
    value: "HONDA",
    label: "HONDA",
  },
  {
    value: "NISSAN",
    label: "NISSAN",
  },
  {
    value: "MAZDA",
    label: "MAZDA",
  },
  {
    value: "MITSUBISHI",
    label: "MITSUBISHI",
  },
  {
    value: "SUBARU",
    label: "SUBARU",
  },
  {
    value: "SUZUKI",
    label: "SUZUKI",
  },
  {
    value: "DAIHATSU",
    label: "DAIHATSU",
  },
  {
    value: "ISUZU",
    label: "ISUZU",
  },
  {
    value: "LEXUS",
    label: "LEXUS",
  },
  {
    value: "HINO",
    label: "HINO",
  },
  {
    value: "MERCEDES BENZ",
    label: "MERCEDES BENZ",
  },
  {
    value: "BMW",
    label: "BMW",
  },
  {
    value: "VOLKSWAGEN",
    label: "VOLKSWAGEN",
  },
  {
    value: "AUDI",
    label: "AUDI",
  },
  {
    value: "VOLVO",
    label: "VOLVO",
  },
];
const CAR_MODEL = [
  { value: "86", label: "86", brand: "TOYOTA" },
  { value: "ALLION", label: "ALLION", brand: "TOYOTA" },
  { value: "ALPHARD", label: "ALPHARD", brand: "TOYOTA" },
  { value: "AQUA", label: "AQUA", brand: "TOYOTA" },
  { value: "AURIS", label: "AURIS", brand: "TOYOTA" },
  { value: "C-HR", label: "C-HR", brand: "TOYOTA" },
  { value: "CAMRY", label: "CAMRY", brand: "TOYOTA" },
  { value: "COASTER", label: "COASTER", brand: "TOYOTA" },
  { value: "COROLLA", label: "COROLLA", brand: "TOYOTA" },
  { value: "CROWN", label: "CROWN", brand: "TOYOTA" },
  { value: "DYNA", label: "DYNA", brand: "TOYOTA" },
  { value: "ESQUIRE", label: "ESQUIRE", brand: "TOYOTA" },
  { value: "ESTIMA", label: "ESTIMA", brand: "TOYOTA" },
  { value: "GR86", label: "GR86", brand: "TOYOTA" },
  { value: "HARRIER", label: "HARRIER", brand: "TOYOTA" },
  { value: "HIACE", label: "HIACE", brand: "TOYOTA" },
  { value: "HILUX", label: "HILUX", brand: "TOYOTA" },
  { value: "ISIS", label: "ISIS", brand: "TOYOTA" },
  { value: "LAND CRUISER PRADO", label: "LAND CRUISER PRADO", brand: "TOYOTA" },
  { value: "LITEACE", label: "LITEACE", brand: "TOYOTA" },
  { value: "MARK II", label: "MARK II", brand: "TOYOTA" },
  { value: "MARK X", label: "MARK X", brand: "TOYOTA" },
  { value: "MIRAI", label: "MIRAI", brand: "TOYOTA" },
  { value: "MR2", label: "MR2", brand: "TOYOTA" },
  { value: "NOAH", label: "NOAH", brand: "TOYOTA" },
  { value: "PASSO", label: "PASSO", brand: "TOYOTA" },
  { value: "PIXIS EPOCH", label: "PIXIS EPOCH", brand: "TOYOTA" },
  { value: "PORTE", label: "PORTE", brand: "TOYOTA" },
  { value: "PREMIO", label: "PREMIO", brand: "TOYOTA" },
  { value: "PRIUS", label: "PRIUS", brand: "TOYOTA" },
  { value: "PROBOX", label: "PROBOX", brand: "TOYOTA" },
  { value: "RAIZE", label: "RAIZE", brand: "TOYOTA" },
  { value: "RAV4", label: "RAV4", brand: "TOYOTA" },
  { value: "REGIUS ACE VAN", label: "REGIUS ACE VAN", brand: "TOYOTA" },
  { value: "ROOMY", label: "ROOMY", brand: "TOYOTA" },
  { value: "SAI", label: "SAI", brand: "TOYOTA" },
  { value: "SCEPTER SEDAN", label: "SCEPTER SEDAN", brand: "TOYOTA" },
  { value: "SIENTA", label: "SIENTA", brand: "TOYOTA" },
  { value: "SPRINTER TRUENO", label: "SPRINTER TRUENO", brand: "TOYOTA" },
  { value: "SUCCEED", label: "SUCCEED", brand: "TOYOTA" },
  { value: "TANK", label: "TANK", brand: "TOYOTA" },
  { value: "TOWNACE", label: "TOWNACE", brand: "TOYOTA" },
  { value: "TOYO ACE", label: "TOYO ACE", brand: "TOYOTA" },
  { value: "TOYOACE", label: "TOYOACE", brand: "TOYOTA" },
  { value: "VANGUARD", label: "VANGUARD", brand: "TOYOTA" },
  { value: "VELLFIRE", label: "VELLFIRE", brand: "TOYOTA" },
  { value: "VITZ", label: "VITZ", brand: "TOYOTA" },
  { value: "VOXY", label: "VOXY", brand: "TOYOTA" },
  { value: "WISH", label: "WISH", brand: "TOYOTA" },
  { value: "YARIS", label: "YARIS", brand: "TOYOTA" },
  { value: "ACCORD", label: "ACCORD", brand: "HONDA" },
  { value: "ACTY TRUCK", label: "ACTY TRUCK", brand: "HONDA" },
  { value: "CIVIC", label: "CIVIC", brand: "HONDA" },
  { value: "FIT", label: "FIT", brand: "HONDA" },
  { value: "FREED", label: "FREED", brand: "HONDA" },
  { value: "GRACE", label: "GRACE", brand: "HONDA" },
  { value: "HONDA", label: "HONDA", brand: "HONDA" },
  { value: "JADE", label: "JADE", brand: "HONDA" },
  { value: "LIFE", label: "LIFE", brand: "HONDA" },
  { value: "N-BOX", label: "N-BOX", brand: "HONDA" },
  { value: "N-ONE", label: "N-ONE", brand: "HONDA" },
  { value: "N-VAN", label: "N-VAN", brand: "HONDA" },
  { value: "N-WGN", label: "N-WGN", brand: "HONDA" },
  { value: "ODYSSEY", label: "ODYSSEY", brand: "HONDA" },
  { value: "SHUTTLE", label: "SHUTTLE", brand: "HONDA" },
  { value: "STEPWAGON", label: "STEPWAGON", brand: "HONDA" },
  { value: "VEZEL", label: "VEZEL", brand: "HONDA" },
  { value: "ZR-V", label: "ZR-V", brand: "HONDA" },
  { value: "ATLAS (CRANE)", label: "ATLAS (CRANE)", brand: "NISSAN" },
  { value: "AURA", label: "AURA", brand: "NISSAN" },
  { value: "DAYZ", label: "DAYZ", brand: "NISSAN" },
  { value: "ELGRAND", label: "ELGRAND", brand: "NISSAN" },
  { value: "FAIRLADY Z", label: "FAIRLADY Z", brand: "NISSAN" },
  { value: "FUGA", label: "FUGA", brand: "NISSAN" },
  { value: "GT-R", label: "GT-R", brand: "NISSAN" },
  { value: "JUKE", label: "JUKE", brand: "NISSAN" },
  { value: "KIX", label: "KIX", brand: "NISSAN" },
  { value: "LEAF", label: "LEAF", brand: "NISSAN" },
  { value: "MURANO", label: "MURANO", brand: "NISSAN" },
  { value: "NOTE", label: "NOTE", brand: "NISSAN" },
  { value: "NT100CLIPPER", label: "NT100CLIPPER", brand: "NISSAN" },
  { value: "ROOX", label: "ROOX", brand: "NISSAN" },
  { value: "SAKURA", label: "SAKURA", brand: "NISSAN" },
  { value: "SERENA", label: "SERENA", brand: "NISSAN" },
  { value: "SILVIA", label: "SILVIA", brand: "NISSAN" },
  { value: "SKYLINE", label: "SKYLINE", brand: "NISSAN" },
  { value: "SYLPHY", label: "SYLPHY", brand: "NISSAN" },
  { value: "TERRANO", label: "TERRANO", brand: "NISSAN" },
  { value: "X-TRAIL", label: "X-TRAIL", brand: "NISSAN" },
  { label: "ATENZA", value: "ATENZA", brand: "MAZDA" },
  { label: "BONGO", value: "BONGO", brand: "MAZDA" },
  { label: "CX-3", value: "CX-3", brand: "MAZDA" },
  { label: "CX-5", value: "CX-5", brand: "MAZDA" },
  { label: "CX-8", value: "CX-8", brand: "MAZDA" },
  { label: "DEMIO", value: "DEMIO", brand: "MAZDA" },
  { label: "FLAIR", value: "FLAIR", brand: "MAZDA" },
  { label: "MAZDA", value: "MAZDA", brand: "MAZDA" },
  { label: "MX-30", value: "MX-30", brand: "MAZDA" },
  { label: "ROADSTER", value: "ROADSTER", brand: "MAZDA" },
  { label: "DELICA", value: "DELICA", brand: "MITSUBISHI" },
  { label: "EK", value: "EK", brand: "MITSUBISHI" },
  { label: "LANCER", value: "LANCER", brand: "MITSUBISHI" },
  { label: "OUTLANDER", value: "OUTLANDER", brand: "MITSUBISHI" },
  { label: "TOWN BOX", value: "TOWN BOX", brand: "MITSUBISHI" },
  { label: "WHEEL LOADER", value: "WHEEL LOADER", brand: "MITSUBISHI" },
  { label: "BRZ", value: "BRZ", brand: "SUBARU" },
  { label: "CHIFFON", value: "CHIFFON", brand: "SUBARU" },
  { label: "CROSSTREK", value: "CROSSTREK", brand: "SUBARU" },
  { label: "FORESTER", value: "FORESTER", brand: "SUBARU" },
  { label: "IMPREZA", value: "IMPREZA", brand: "SUBARU" },
  { label: "LEGACY", value: "LEGACY", brand: "SUBARU" },
  { label: "OUTBACK", value: "OUTBACK", brand: "SUBARU" },
  { label: "LEVORG", value: "LEVORG", brand: "SUBARU" },
  { label: "PLEO PLUS", value: "PLEO PLUS", brand: "SUBARU" },
  { label: "SAMBAR", value: "SAMBAR", brand: "SUBARU" },
  { label: "STELLA", value: "STELLA", brand: "SUBARU" },
  { label: "XV", value: "XV", brand: "SUBARU" },
  { label: "ALTO", value: "ALTO", brand: "SUZUKI" },
  { label: "CARRY", value: "CARRY", brand: "SUZUKI" },
  { label: "EVERY", value: "EVERY", brand: "SUZUKI" },
  { label: "HUSTLER", value: "HUSTLER", brand: "SUZUKI" },
  { label: "IGNIS", value: "IGNIS", brand: "SUZUKI" },
  { label: "JIMNY", value: "JIMNY", brand: "SUZUKI" },
  { label: "SOLIO", value: "SOLIO", brand: "SUZUKI" },
  { label: "SPACIA", value: "SPACIA", brand: "SUZUKI" },
  { label: "SUPER CARRY", value: "SUPER CARRY", brand: "SUZUKI" },
  { label: "SWIFT", value: "SWIFT", brand: "SUZUKI" },
  { label: "WAGON R", value: "WAGON R", brand: "SUZUKI" },
  { label: "XBEE", value: "XBEE", brand: "SUZUKI" },
  { label: "スズキバイク", value: "スズキバイク", brand: "SUZUKI" },
  { label: "ワゴンR SMILE", value: "ワゴンR SMILE", brand: "SUZUKI" },
  { label: "ATRAI", value: "ATRAI", brand: "DAIHATSU" },
  { label: "CAST", value: "CAST", brand: "DAIHATSU" },
  { label: "COPEN", value: "COPEN", brand: "DAIHATSU" },
  { label: "HIJET", value: "HIJET", brand: "DAIHATSU" },
  { label: "MIRA E:S", value: "MIRA E:S", brand: "DAIHATSU" },
  { label: "MOVE", value: "MOVE", brand: "DAIHATSU" },
  { label: "TAFT", value: "TAFT", brand: "DAIHATSU" },
  { label: "TANTO", value: "TANTO", brand: "DAIHATSU" },
  { label: "THOR", value: "THOR", brand: "DAIHATSU" },
  { label: "WAKE", value: "WAKE", brand: "DAIHATSU" },
  { label: "CT", value: "CT", brand: "LEXUS" },
  { label: "GS350", value: "GS350", brand: "LEXUS" },
  { label: "HS", value: "HS", brand: "LEXUS" },
  { label: "LS", value: "LS", brand: "LEXUS" },
  { label: "LS500h", value: "LS500h", brand: "LEXUS" },
  { label: "LS600hL", value: "LS600hL", brand: "LEXUS" },
  { label: "NX", value: "NX", brand: "LEXUS" },
  { label: "NX300h", value: "NX300h", brand: "LEXUS" },
  { label: "RX450h", value: "RX450h", brand: "LEXUS" },
  { label: "RX450hL", value: "RX450hL", brand: "LEXUS" },
  { label: "SC", value: "SC", brand: "LEXUS" },
  { label: "DUTRO", value: "DUTRO", brand: "HINO" },
  { : "PROFIA", value: "PROFIA", brand: "HINO" },
  { label: "RANGER", value: "RANGER", brand: "HINO" },

  { label: "A-CLASS", value: "A-CLASS", brand: "MERCEDES BENZ" },
  { label: "C-CLASS", value: "C-CLASS", brand: "MERCEDES BENZ" },
  { label: "CLA-CLASS", value: "CLA-CLASS", brand: "MERCEDES BENZ" },
  { label: "E-CLASS", value: "E-CLASS", brand: "MERCEDES BENZ" },
  { label: "GLA-CLASS", value: "GLA-CLASS", brand: "MERCEDES BENZ" },
  { label: "GLC-CLASS", value: "GLC-CLASS", brand: "MERCEDES BENZ" },
  { label: "GLC220d", value: "GLC220d", brand: "MERCEDES BENZ" },
  { label: "GLE", value: "GLE", brand: "MERCEDES BENZ" },
  { label: "S-CLASS", value: "S-CLASS", brand: "MERCEDES BENZ" },
  { label: "TRANSPORTER", value: "TRANSPORTER", brand: "MERCEDES BENZ" },

  { label: "1 SERIES", value: "1 SERIES", brand: "BMW" },
  { label: "2 SERIES", value: "2 SERIES", brand: "BMW" },
  { label: "3 SERIES", value: "3 SERIES", brand: "BMW" },
  { label: "318i", value: "318i", brand: "BMW" },
  { label: "4 SERIES", value: "4 SERIES", brand: "BMW" },
  { label: "740i", value: "740i", brand: "BMW" },
  { label: "MINI", value: "MINI", brand: "BMW" },
  { label: "X2", value: "X2", brand: "BMW" },
  { label: "X3", value: "X3", brand: "BMW" },
  { label: "X4", value: "X4", brand: "BMW" },

  { label: "GOLF", value: "GOLF", brand: "VOLKSWAGEN" },
  { label: "POLO", value: "POLO", brand: "VOLKSWAGEN" },
  { label: "SHARAN", value: "SHARAN", brand: "VOLKSWAGEN" },
  { label: "T-Roc", value: "T-Roc", brand: "VOLKSWAGEN" },
  { label: "BEETLE", value: "BEETLE", brand: "VOLKSWAGEN" },
  { label: "TIGUAN", value: "TIGUAN", brand: "VOLKSWAGEN" },

  { label: "A3", value: "A3", brand: "AUDI" },
  { label: "A4", value: "A4", brand: "AUDI" },
  { label: "Q3", value: "Q3", brand: "AUDI" },
  { label: "Q5", value: "Q5", brand: "AUDI" },
  { label: "RS Q3", value: "RS Q3", brand: "AUDI" },

  { label: "V40", value: "V40", brand: "VOLVO" },
  { label: "V60", value: "V60", brand: "VOLVO" },
  { label: "XC40", value: "XC40", brand: "VOLVO" },
  { label: "XC60", value: "XC60", brand: "VOLVO" },

  { label: "ELF", value: "ELF", brand: "ISUZU" },
  { label: "FORWARD", value: "FORWARD", brand: "ISUZU" },
  { label: "GIGA", value: "GIGA", brand: "ISUZU" },
];
const SYSTEM = [
  {
    label: "2WD",
    value: "2WD",
  },
  {
    label: "4WD",
    value: "4WD",
  },
];
const FUEL = [
  {
    label: "Hybrid",
    value: "Hybrid",
  },
  {
    label: "Gasoline",
    value: "Gasoline",
  },
  {
    label: "Diesel",
    value: "Diesel",
  },
];
const DAMAGE = [
  {
    label: "Rolling",
    value: "Rolling",
  },
  {
    label: "Not Rolling",
    value: "Not Rolling",
  },
  {
    label: "Driveable",
    value: "Driveable",
  },
];
export { CAR_MARK, CAR_MODEL, SYSTEM, FUEL, DAMAGE };
