export default asapList = [
  {
    company: "Хаан банкны 5172 дугаар салбар",
    plate: "2581УНВ",
    classification: "Суудлын",
    mark: "Volkswagen",
    model: "Passat",
    color: "Хар",
    acitivity: "Ажлын хэрэгцээнд",
    driver: "Жолооч Цэвээнсодномын Самданбазар СА73122615",
  },
  {
    company: "Хас банкны 59 дүгээр салбар",
    plate: "9372УАХ ",
    classification: "Суудлын ",
    mark: "Toyota ",
    model: "Belta ",
    color: "Саарал ",
    acitivity: "Ажлынхэрэгцээнд",
    driver: "Жолооч Думаагийн Даваадорж ЧЗ72032016",
  },
  {
    company: "Худалдаа хөгжлийн банкы Буянт-Ухаа салбар",
    plate: "2011УАА",
    classification: "Суудлын ",
    mark: "Toyota",
    model: "Aqua",
    color: "Цагаан",
    acitivity: "Ажлынхэрэгцээнд",
    driver: "Жолооч Жагваралдоржийн Одхүү КЮ58072518",
  },
  {
    company: "Бичил глобус ББСБ",
    plate: "7703УНЧ ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Harrier",
    color: "Хар",
    acitivity: "Ажлынхэрэгцээнд",
    driver: "Ажилтан Болдбаатарын Доржсүрэн ГЗ88020719 Утас 99109300",
  },
  {
    company: "Бичил глобус ББСБ",
    plate: "9117УНК",
    classification: "Суудлын",
    mark: "Kia",
    model: "K-5",
    color: "Хар",
    acitivity: "Дотоод үйл ажиллагаанд",
    driver: "Нямдорж Чинзориг /ЧМ23061072/",
  },
  {
    company: "Бичил глобус ББСБ",
    plate: "3759УАК",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Prius 40",
    color: "Сувдан цагаан",
    acitivity: "Зээлийн эдийн засаг нарт ",
    driver: "Жанцан Баярмаа /ХЕ61052117/",
  },
  {
    company: "Бичил глобус ББСБ",
    plate: "2054УЕО",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Prius 30",
    color: "Хар саарал",
    acitivity: "Ажлын хэрэгцээнд",
    driver: "",
  },
  {
    company: "Бичил глобус ББСБ",
    plate: "0831УНҮ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Prius 30",
    color: "Цагаан",
    acitivity: "Ажлынхэрэгцээнд",
    driver: "Эдийн засагч Лувсандандар Төрням ИН97021616 утас: 80001564",
  },
  {
    company: "Бичил глобус ББСБ",
    plate: "9473УНЕ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Rumion",
    color: "Цэнхэр",
    acitivity: "Захиралын хэрэгцээнд",
    driver: "Ахлах мэргэжилтэн Намсрай Энх-Орчлон УШ93092923 утас: 90020053",
  },
  {
    company: "Бичил глобус ББСБ",
    plate: "1582УНУ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Corolla",
    color: "Цагаан",
    acitivity: "Ажлынхэрэгцээнд",
    driver: "Ц.Эрдэнэбаяр, Гэрээтжолооч, УЖ63022310",
  },
  {
    company: "Бичил глобус ББСБ",
    plate: "7444УНҮ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Prado 150",
    color: "Хар",
    acitivity: "Албан хэрэгцээнд",
    driver: "Ж.Хуягбаатар /МЭ69110917/",
  },
  {
    company: "Үйзэн ивээлт ББСБ",
    plate: "0945убо",
    classification: "Суудал",
    mark: "Тоуоtа",
    model: "СROWN/210/",
    color: "цагаан",
    acitivity: "Харилцагчдын үйлчилгээнд",
    driver: "Амгалан-Энхийн Алтжин /рд:уш99070127/. менежер",
  },
  {
    company: "Үйзэн ивээлт ББСБ",
    plate: "0968убч",
    classification: "Суудал",
    mark: "Toyota",
    model: "Prius 20",
    color: "Хар",
    acitivity: "Тусгай активын ажилд",
    driver: "Батдэлгэрийн Батбаяр/рд:йю87101933/",
  },
  {
    company: "Хэрлэн онон туул",
    plate: "2424унб",
    classification: "Суудлын",
    mark: "РогО",
    model: "1оигпео",
    color: "Мөнгөлөг",
    acitivity: "Захирлын албан хэрэгцээнд",
    driver: "Б.Цүгэрсүрэн/рд:уу9003133 эдийн засагч",
  },
  {
    company: "Хэрлэн онон туул",
    plate: "0457убд",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Probox",
    color: "Цагаан",
    acitivity: "Ажилчдын албан хэрэгцээнд",
    driver: "Ч Төртогтох. /ум95071459/, хуульч",
  },
  {
    company: "Хэрлэн онон туул",
    plate: "9901унн",
    classification: "Туулах чадаар сайтай",
    mark: "Toyota",
    model: "LandCriuser 200",
    color: "Шаргал ",
    acitivity: "Захирлын албан хэрэгцээнд",
    driver: "Ч Төртогтох. /ум93071459/.хуульч",
  },
  {
    company: "Хэрлэн онон туул",
    plate: "8640убм",
    classification: "Гэр бүлийн",
    mark: "Тоуо1а",
    model: "Alphard",
    color: "Сувдан цагаан",
    acitivity: "Ажилчдын албан хэрэгцээнд",
    driver: "Ж.Амарбаясгалан. /чц88032674/. эдийн засагч",
  },
  {
    company: "Цогзол Финанс",
    plate: "6655уа-",
    classification: "Туулах чадвар сайтай",
    mark: "Toyota ",
    model: "LandCriuser 200 ",
    color: "Хар саарал",
    acitivity: "Захирлын албан хэрэгцээнд",
    driver: "Даланбаярь н Алтансүх /рд: АЭ82030376/, жолооч",
  },

  {
    company: "Хаан банк",
    acitivity: "Алтаргана",
    plate: "0994УНГ",
    mark: "Тоёота",
    model: "приус-20",
    classification: "Суудал",
    color: "Сувдан цагаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Амгалан",
    plate: "5754УАТ",
    mark: "Приус",
    model: "Альфа",
    classification: "Суудал",
    color: "Сувдан цагаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "17-ийн буудал",
    plate: "5283УНЕ",
    mark: "Тоёота",
    model: "приус-20",
    classification: "Суудал",
    color: "Ногоон",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "11-р дүгээр хороолол",
    plate: "6634УАЕ",
    mark: "Toyota",
    model: "Vanguard",
    classification: "Дунд овор",
    color: "Хар саарал",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "АНДУУД ТТ",
    plate: "2362УЕН",
    mark: "Тоёота",
    model: "Акуа",
    classification: "Суудал",
    color: "Сувдан цагаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Байг тойруу",
    plate: "8250УЕМ",
    mark: "Королла",
    model: "Пиелдер",
    classification: "Суудал",
    color: "Сувдан цагаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Барс ТТ",
    plate: "9473УНЕ",
    mark: "Королла",
    model: "Румион",
    classification: "Суудал",
    color: "Хөх",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Баянмонгол",
    plate: "9735УАО",
    mark: "Тоёота",
    model: "приус-30",
    classification: "Суудал",
    color: "Мөнгөлөг",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Баянгол салбар",
    plate: "0572УНЦ ",
    mark: "Терех",
    model: "ТР60 ",
    classification: "Өрөө буулгагч ",
    color: "Цагаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "БЗТТ",
    plate: "2272УБТ",
    mark: "Нуипба",
    model: "Соип1гу",
    classification: "Ачааны",
    color: "Шаргал",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "БЗ салбар",
    plate: "8159УНЦ",
    mark: "Тоёота",
    model: "Акуа",
    classification: "Суудал",
    color: "Хар саарал",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Баянхошуу ТТ",
    plate: "5946УБМ",
    mark: "Приус",
    model: "Альфа",
    classification: "Суудал",
    color: "Хар саарал",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Бичил",
    plate: "3015УНС",
    mark: "Приус",
    model: "Альфа",
    classification: "Суудал",
    color: "Хар саарал",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Бөхийн Өргөө",
    plate: "5120УНД",
    mark: "Тоёота",
    model: "приус-30",
    classification: "Суудал",
    color: "Хар",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Да-Хүрээ",
    plate: "3452УБЕ",
    mark: "Ланд",
    model: "крузер 200",
    classification: "Жиип",
    color: "Цагаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "ДарханПлаза",
    plate: "5195УНӨ",
    mark: "Тоёота",
    model: "приус-20",
    classification: "Суудал",
    color: "Мөнгөлөг саарал",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Дарь-Эх",
    plate: "4278УЕЕ",
    mark: "Приус",
    model: "Альфа",
    classification: "Суудал",
    color: "Хар саарал",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Их цайз",
    plate: "7160УЕК",
    mark: "Приус",
    model: "Альфа",
    classification: "Суудал",
    color: "Мөнгөлөг",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Модны 2 ТТ",
    plate: "6739УНЛ",
    mark: "Тоёота",
    model: "лриус-30",
    classification: "Суудал",
    color: "Ягаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "МУИС",
    plate: "4373УБТ",
    mark: "МегзеСев",
    model: "еЗОО",
    classification: "Суудал",
    color: "Мөнгөлөг саарал",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Намянжү",
    plate: "3871УНӨ",
    mark: "Тоёота",
    model: "приус-30",
    classification: "Суудал",
    color: "Мөнгөлөг",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Нарлаг Дэнж",
    plate: "2516УАО",
    mark: "Тоёота",
    model: "приус-30",
    classification: "Суудал",
    color: "Хар",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Номин юнайтед",
    plate: "6766УБЭ",
    mark: "Тоёота",
    model: "королла",
    classification: "Суудал",
    color: "Мөнгөлөг",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Оргил стар",
    plate: "3868УБП",
    mark: "Тоёота",
    model: "Ахио",
    classification: "Суудал",
    color: "Цэнхэр",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Офицер",
    plate: "6446УББ",
    mark: "Тоёота",
    model: "приус-20",
    classification: "Суудал",
    color: "Мөнгөлөг",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Ривер гарден",
    plate: "9905УНВ",
    mark: "Нопба",
    model: "1П51дЫ",
    classification: "Суудал",
    color: "Сувдан цагаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Сакура",
    plate: "8365УБЗ",
    mark: "Тоёота",
    model: "Акуа",
    classification: "Суудал",
    color: "иайвар цэнхэр",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Сансар",
    plate: "6657УАН",
    mark: "Королла",
    model: "Пиелдер",
    classification: "Суудал",
    color: "Цагаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Соёлын төв өргөө",
    plate: "8936УБД",
    mark: "Тоёота",
    model: "приус-30",
    classification: "Суудал",
    color: "Саарал",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Сонсоголон",
    plate: "6219УБЦ",
    mark: "Приус",
    model: "Альфа",
    classification: "Суудал",
    color: "Үзмэн ягаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "СБ Салбар",
    plate: "8062УБЗ",
    mark: "Мззап",
    model: "ХТгаП",
    classification: "Дунд овор",
    color: "Хар",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Сүхбаатар ТТ",
    plate: "4859УНӨ",
    mark: "Ьехиз",
    model: "Рз25И",
    classification: "Суудал",
    color: "Сувдан цагаан",
    driver: "",
  },
  {
    company: "Хаан банк",
    acitivity: "Сэлбэ",
    plate: "1465УЕЕ",
    mark: "Тоёота",
    model: "приус-30",
    classification: "Суудал",
    color: "Мөнгөлөг",
    driver: "",
  },
  {
    company: "Голомт банк ",
    plate: "9501УБҮ ",
    classification: "суудЛЫН",
    mark: "Toyota",
    model: "Parado 150",
    color: "Саарзл",
    acitivity: "Албан хэрэгцээнд",
    driver: "Амгалан Энхбаатар ЕК78081678, жолооч53.",
  },
  {
    company: "Хаан банк",
    plate: "7411УМН ",
    classification: "Суудал",
    mark: "Toyared",
    model: "Toyared",
    color: "Xap",
    acitivity: "Албан хзрэгцээнд",
    driver: "Батзориг Нармандах ЕК92031717, жолооч",
  },
  {
    company: "Хаан банк",
    plate: "0094дгн",
    classification: "Суудал",
    mark: "Toyata",
    model: "Land cruiser -76",
    color: "Xap саарал",
    acitivity: "Албан хэрэгцээнд",
    driver: "Лхамсүрэн Анхбаяр ЕЭ69111471, Жолооч",
  },
  {
    company: "Хаан банк",
    plate: "0093ДГН",
    classification: "Суудал",
    mark: "Toyata",
    model: "Land cruiser -200",
    color: "Xap саарал",
    acitivity: "Албан хэрэгцэзнд",
    driver: "Сугаржав Эрхэмжаргал ЕК89031175, Жолооч",
  },
  {
    company: "Төрийн банк",
    plate: "7411УМН",
    classification: "Суудал",
    mark: "Toyared",
    model: "Toyared",
    color: "Xap",
    acitivity: "Албан хзрэгцээнд ",
    driver: "Намдаг Одгэрэл КЮ700Ө2131",
  },
  {
    company: "Төрийн банк",
    plate: "0094дгн",
    classification: "Суудал",
    mark: "Toyata",
    model: "Land cruiser -76",
    color: "Xap саарал",
    acitivity: "Албан хэрэгцээнд",
    driver: "Намдаг Одгэрэл КЮ700Ө2131",
  },
  {
    company: "Хас банк",
    plate: "0063ДГС",
    classification: "Суудал",
    mark: "Toyata",
    model: "Land cruiser 76",
    color: "Цагаан",
    acitivity: "Албан хэрэгцээнд",
    driver: "ДоржсэмбэБатчулууиЕ374061411 Жолооч",
  },
  {
    company: "Голомт банк",
    plate: "3974УАС",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Prado 150",
    color: "Xap хөх",
    acitivity: "апбан хэрэгцээнд",
    driver: "Батмөнхийн Батболд/ВН75072918/ жопооч",
  },
  {
    company: "Төрийн банк",
    plate: "7621УНӨ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Land cruiser 76 ",
    color: "Цагаан",
    acitivity: "апбан хэрэгцээнд",
    driver: "Гамбагыи Цэвэгмид/СМ90051313/ ЖОЛООЧ",
  },
  {
    company: "Хаан банк",
    plate: "3325УНН",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Prado 150",
    color: "Xap хөх",
    acitivity: "апбан хэрэгцээнд",
    driver: "Мөнхоишиин Мөихбалт /ЖЯ820Э2474/ ЖОЛООЧ",
  },
  {
    company: "Хаан банк",
    plate: "0272УНМ",
    classification: "Суудлын",
    mark: "Volkswagen",
    model: "Touareg",
    color: "Xap",
    acitivity: "апбан хэрэгцээнд",
    driver: "Зоригтбаатарын Гантулга/ИП91072811/ ЖОЛООЧ",
  },
  {
    company: "Бичил глобус ББСБ",
    plate: "1701УЕМ",
    classification: "Суудлым",
    mark: "Toyota",
    model: "Приус-30",
    color: "Хар",
    acitivity: "Албан хэрэгцээид",
    driver: "Ургнасангийн Даваажаргал (ЙВ99051110), 83107596",
  },
  {
    company: "Хаан банк",
    plate: "2516УАО",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Приус-30 ",
    color: "Хар",
    acitivity: "Албан хэрэгцээнд",
    driver: "Лхагважавын Өсөхбаяр (ЖЭ88020810). 99964454",
  },
  {
    company: "Хас банк",
    plate: "1374УАВ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Приус-20",
    color: "Хар",
    acitivity: "Албан хэрэгцээнд",
    driver: "Оргойн Ганхөлөг (ЛЮ82032211), 99056996 ",
  },
  {
    company: "Хас банк",
    plate: "3455УБЯ",
    classification: "Суулдлын",
    mark: "Toyota",
    model: "Приус-20",
    color: "Цагаан",
    acitivity: " Албан хэрэгцээнд",
    driver: "Д.Гантөмөр /НМ72061828/",
  },
  {
    company: "Хаан банк",
    plate: "2510УЕВ",
    classification: "Суулдлын",
    mark: "Toyota",
    model: "Приус-20",
    color: "Цагаан",
    acitivity: "Албан хэрэгцээнд",
    driver: "",
  },
  {
    company: "Инвестор ББСБ",
    plate: "8695УЕВ",
    classification: "Суулдлын",
    mark: "Toyota",
    model: "Приус-30",
    color: "Усан цэнхэр",
    acitivity: "Албан хэрэгцээнд",
    driver: "Бүх ажилтан ашиглах боломжтой",
  },
  {
    company: "Тэсийн шугуй ББСБ",
    plate: "9913УЕА",
    classification: "Суулдлын",
    mark: "Toyota",
    model: "Приус-20",
    color: "Бор шаргал",
    acitivity: "Албан хэрэгцээнд",
    driver: "Э.Эрдэнэтунгалаг",
  },
  {
    company: "Хаан банкны 5172 дугаар салбар",
    plate: "2581УНВ",
    classification: "Суудлын",
    mark: "Volkswagen",
    model: "Passat",
    color: "xap",
    acitivity: "Албан хэрэгцээнд",
    driver: "Цэвээнсодном овоггой СамданбазарРД:СА73122615 Жолооч",
  },
  {
    company: "Хас банкны 59 дүгээр салбар",
    plate: "9372УАХ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "belta",
    color: "саарал",
    acitivity: "Албан хэрэгцээнд",
    driver: "Думаа овогтой Даваадорж РД:Ч372032016 Жолооч",
  },
  {
    company: "Худалдаа хөгжлийн банкны Буянт-Ухаа салбар",
    plate: "2011УАА",
    classification: "Суудлын",
    mark: "Toyota",
    model: "aqua",
    color: "цагаан",
    acitivity: "Албан хэрэгцээнд",
    driver: "",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "8440УБВ",
    classification: "Суудал",
    mark: "Toyota",
    model: "Harrier",
    color: "Сувдан цагаан",
    acitivity: "Захирлын албан хэрэгцээнд",
    driver: "Сэргэлэнгийн Бямбажаргал/РД:ИБ96071309/",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "2105ОРБ",
    classification: "Суудал",
    mark: "Toyota",
    model: "Prius",
    color: "Хар",
    acitivity: "Захирлын албан хэрэгцээнд",
    driver: "Ванчинхүүгийн Маргад/РД:ФА93052339/",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "1488УБК",
    classification: "Суудал",
    mark: "Toyota",
    model: "Vellfire",
    color: "Сувдан цагаан",
    acitivity: "Албан хэрэгцээнд",
    driver: "Пүрэвийн Мөнгөнхуяг /РД:С380062611/",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "4299УНУ",
    classification: "Суудал",
    mark: "Toyota",
    model: "Crown ",
    color: "Хөх",
    acitivity: "Захирлын албан хэрэгцээнд",
    driver: "Мөнхжаргалын Энхмэнд /РД:Ч387111576/",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "4872УБУ",
    classification: "Суудал",
    mark: "Volksvagen",
    model: "Passat",
    color: "Хар",
    acitivity: "Захирлын албан хэрэгцээнд",
    driver: "СаяннямбынСанги /РД:ВР77031312/",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "0143УЕВ ",
    classification: "Суудал",
    mark: "Lexus",
    model: "RX450h",
    color: "Хар",
    acitivity: "Албан хэрэгцээнд",
    driver: "БаярсайханыМэнтүг /АЭ84091778/",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "4721УАН",
    classification: "Суудлын",
    mark: "Тоёота",
    model: "Приүс 20",
    color: "Цагаан",
    acitivity: "Албан хэрэгцээнд",
    driver: "Менежер, зээлийн мэргэжилтэн Б.Бат-Эрдэнэ (РД:ИД95091617)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "6657УАН",
    classification: "Суудлын",
    mark: "Corolla",
    model: "fielder",
    color: "цагаан",
    acitivity: "Албан хэрэгцээнд",
    driver: "Жолооч Дагвабүслүүрийн Ганзориг (РД:ЖЮ66051713)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "7598УЕМ",
    classification: "Суудлын",
    mark: "Lexus",
    model: "HS250",
    color: "Хар",
    acitivity: "Хувийн автомашин",
    driver: "Амархүү овогтой ПүрэвОчир, Санхүүгийн зөвлөх",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "9144УЕВ",
    classification: "Суудлын",
    mark: "Сонота",
    model: "К-5",
    color: "Хар-хөх",
    acitivity: "Захирлын албан хэрэгцээнд",
    driver: "Жолооч Сэрээндоржын Эрдэнэдоржсүрэн (РД:НЧ64011516)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "8076УБЕ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Prius-41",
    color: "цагаан",
    acitivity: "албан хэрэгцээнд ",
    driver: "Ажилтнуудын Жолооч Шарын Ганболд (РД:ЙЮ61010717)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "3933УЕА",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Land Cruiser 300",
    color: "Сувдан цагаан",
    acitivity: "Захирлын албан хэрэгцээнд",
    driver: "Захирал Бямбын БаатарЭрдэнэ (РД:УЮ920511918)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "6080УНЗ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Land Cruiser 200",
    color: "Хар саарал",
    acitivity: "Албан хэрэгцээнд",
    driver: "Захирал Манилжавын Чанзавцог (РД:АЯ91012215)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "8604УБС",
    classification: "Суудлын",
    mark: "Тоёота",
    model: "приус 10",
    color: "Сувдан цагаан",
    acitivity: "Албан хэрэгцээнд",
    driver: "Жолооч Тодмагнайгийн Цодоо(РД:ЦЕ54030879)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "9912УНЛ",
    classification: "суудлын",
    mark: "Тоёота",
    model: "Приус 30",
    color: "Сувдан цагаан ",
    acitivity: "Албан хэрэгцээнд",
    driver: "Эдийн засагч Мөнхбаярын Төгсбаяр(РД:У398053110)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "4694УАМ",
    classification: "суудлын",
    mark: "Тоёота",
    model: "Приус-30",
    color: "Сувдан цагаан",
    acitivity: "Албан хэрэгцээнд",
    driver: "Эдийн засагч Ганбатын Золжаргал (РД:ЕП79040616)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "3965УЕЕ",
    classification: "суудлын",
    mark: "Тоёота",
    model: "Приус-41",
    color: "Сувда цагаан",
    acitivity: "Албан хэрэгцээнд",
    driver: "Эдийн засагч Ганболдын Буянхишиг (РД:ЁЙ93040114)",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "9472УНП",
    classification: "Суудлын",
    mark: "Киа",
    model: "Серанто",
    color: "Мөнгөлөг саарал",
    acitivity: "Захиралын албан хэрэгцээнд",
    driver: "Одоогоор жолооч байхгүй.",
  },
  {
    company: "Тэмдэглэгдээгүй",
    plate: "2658УАВ ",
    classification: "Суудлын ",
    mark: "Toyota",
    model: "Приус 40 ",
    color: "Мөнгөлөгсаарал",
    acitivity: "Захиралын болон албан хаагчдын албан хэрэгцээнд ашиглагддаг.",
    driver: "Тогтсон жолооч байхгүй.",
  },
  {
    company: "Хас банк",
    plate: "0284УНХ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Prius-20",
    color: "Саарал",
    acitivity: "Ажилчдын албан хэрэгцээнд",
    driver: "",
  },
  {
    company: "Хаан банк",
    plate: "5091УЕЕ",
    classification: "Суудлын",
    mark: "Toyota",
    model: "Wish",
    color: "Мөнгөлөг саарал",
    acitivity: "Ажилчдын албан хэрэгцээнд",
    driver: "",
  },
  {
    company: "Төрийнбанк",
    plate: "9275УНВ",
    classification: "Суудлын",
    mark: "Ланд",
    model: "крузер 76",
    color: "Саарал",
    acitivity: "Бэлэн мөнгө тээвэрлэхэд",
    driver:
      "Жанцийн Буянтогтох /РД XЛ69061411/ Жолооч албам тушаалтай Утас 9906425",
  },
  {
    company: "Хаан банк",
    plate: "2653УБЯ",
    classification: "Суудлын",
    mark: "Киа ",
    model: "K5",
    color: "Саарал",
    acitivity: "Албан хэрэгцээнд",
    driver: "Гончиг Мөнхбаяр /РД ЧР74050911/ Жолооч тушаалтай утас9918418917",
  },
  {
    company: "Төрийн банк",
    plate: "8961УНП",
    classification: "Суудлын",
    mark: "Киа",
    model: "Серато",
    color: "Саарал",
    acitivity: "Албанхэрэгцээнд",
    driver:
      "Маргид Отгонбаяр /РД ДК70010518/ Жолооч албан тушаалтай утас-95290088",
  },
];
