require("dotenv").config({
  path: "./.env",
});
const path = require("path");

const resolveUploadsRoot = () => {
  const configuredRoot = process.env.UPLOADS_ROOT;

  if (!configuredRoot) {
    return path.resolve("uploads");
  }

  return path.resolve(configuredRoot);
};

module.exports = {
  DB: process.env.DB,
  // DB: "mongodb://localhost:27017/?retryWrites=true&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000",
  ALLOWED_ORIGINS: [
    "http://localhost:3000",
    "http://localhost:3305",
    "https://rfid-odt.vercel.app/",
    "http://vil.odt.mn/",
    "http://localhost:3305",
    "http://103.9.90.140/",
    "http://103.9.90.140:3305/",
    "http://103.9.90.140:3305",
  ],
  TIME_OUT: 3000,
  PROJECT_NAME: process.env.npm_package_config_domain,
  PROJECT_PORT: process.env.npm_package_config_port,
  XYP: "http://vil.odt.mn:5002",
  // XYP: "http://localhost:80/xyp/invoker.php",
  // XYP: "http://103.9.90.140:80/xyp/invoker.php",
  JWT: { secret: process.env.SECRET_KEY, algorithms: ["HS256"] },
  SECRET: process.env.SECRET_KEY,
  UPLOADS_ROOT: resolveUploadsRoot(),
  BASIC_AUTH: {
    username: process.env.BASIC_AUTH_USERNAME,
    password: process.env.BASIC_AUTH_PASSWORD,
  },
  EXPIRE: {
    expiresIn: "12h",
  },
  DEMO: false,
  ODT_USERNAME: "OrgilTradeService",
  ODT_PASSWORD: "JA7cabasUZ36Pz694ZnDE4vadXnXymHF",
  DOMAIN: "",
  PHOTO_ROOT: "http://202.126.92.138/",
  VIOLATION_LAWS: [
    {
      law_name: "Зөрчлийн тухай хууль",
      law_section: "11.15-7",
      law_text: "Зөрчлийн тухай хууль 11.15-7",
      law: "Жолоочийн даатгалд хамруулалгүйгээр тээврийн хэрэгслээ ашиглан замын хөдөлгөөнд оролцсон",
      amount: "0",
      amount_text: "0₮",
      type: "insurance",
    },
    {
      law_name: "Зөрчлийн тухай хууль",
      law_section: "14.7-10.2,10.3",
      law_text: "Зөрчлийн тухай хууль 14.7-10.2,10.3",
      law: "Техникийн хяналтын үзлэгт оруулаагүй тээврийн хэрэгслээр замын хөдөлгөөнд оролцсон",
      amount: "50000",
      amount_text: "50000₮",
      type: "inspection",
    },
    {
      law_name: "Зөрчлийн тухай хууль",
      law_section: "14.7-31",
      law_text: "Зөрчлийн тухай хууль 14.7-31",
      law: "Тээврийн хэрэгслийн тогтоосон хурдыг 10-50 хүртэл хувиар хэтрүүлсэн",
      amount: "50000",
      amount_text: "50000₮",
      type: "speed",
    },
    {
      law_name: "Зөрчлийн тухай хууль",
      law_section: "14.7-20",
      law_text: "Зөрчлийн тухай хууль 14.7-20",
      law: "Хамгаалах бүс хэрэглээгүй",
      amount: "20000",
      amount_text: "20000₮",
      type: "speed",
    },
  ],
  UB: [
    "УНӨ",
    "УНҮ",
    "УНЯ",
    "УНЭ",
    "УНЧ",
    "УНЦ",
    "УНХ",
    "УНУ",
    "УНТ",
    "УНС",
    "УНР",
    "УНП",
    "УНО",
    "УНН",
    "УНМ",
    "УНЛ",
    "УНК",
    "УНИ",
    "УНЗ",
    "УНЕ",
    "УНД",
    "УНГ",
    "УНВ",
    "УНБ",
    "УНЙ",
    "УЕК",
    "УЕЕ",
    "УЕВ",
    "УЕА",
    "УБӨ",
    "УБҮ",
    "УБЯ",
    "УБЭ",
    "УБЧ",
    "УБЦ",
    "УБХ",
    "УБУ",
    "УБТ",
    "УБС",
    "УБР",
    "УБП",
    "УБО",
    "УБН",
    "УБМ",
    "УБЛ",
    "УБК",
    "УБИ",
    "УБЗ",
    "УБЕ",
    "УБД",
    "УБГ",
    "УБВ",
    "УББ",
    "УБА",
    "УАХ",
    "УАУ",
    "УАТ",
    "УАС",
    "УАР",
    "УАО",
    "УАН",
    "УАМ",
    "УАК",
    "УАЕ",
    "УАВ",
    "УАА",
    "БРА",
    "НАА",
    "УЕН",
    "УЕМ",
    "УУБ",
    "УЕО",
    "УАБ",
    "УЕУ",
    "ДК",
  ],
};
export const checkViolation = (type) => {
  // return VIOLATION_LAWS.find((row) => row.type == type);
  return {
    law_name: "Зөрчлийн тухай хууль",
    law_section: "14.7-20",
    law_text: "Зөрчлийн тухай хууль 14.7-20",
    law: "Хамгаалах бүс хэрэглээгүй",
    amount: "20000",
    amount_text: "20000₮",
    type: "speed",
  };
};
